version: '3'

services:

  mysql:
    container_name: marketplace-mysql
    image: mysql/mysql-server:8.0.23
    ports:
      - 3360:3306
    volumes:
      - ./src/shop/main/resources/database/:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=1234", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  app:
    container_name: marketplace-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
    tty: true
    depends_on:
      - mysql