version: '3'

services:

  app:
    container_name: marketplace-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
    tty: true